#!/usr/bin/python
# This script can be used to sync the production releases which are
# declared as announced in the tag collector and 
from optparse import OptionParser
from commands import getstatusoutput
from sys import exit
import urllib2
try:
  import json
except:
  import simplejson as json

def getAnnouncedReleases(query={}):
  url = "https://cmssdt.cern.ch/tc/getReleasesInformation"
  query = "&".join("%s=%s" % x for x in query.iteritems())
  results = urllib2.urlopen(url + "?" + query)
  data = json.loads(results.read())
  return data["data"].keys()

def withGridEnv(command, **kwds):
  opts = {"environment": "/afs/cern.ch/cms/LCG/LCG-2/UI/cms_ui_env.sh",
          "command": command % kwds}
  return getstatusoutput("source %(environment)s ; %(command)s" % opts)

def availableCes():
  error, out = withGridEnv("lcg-info --vo cms --list-ce"
                           " --query 'Cluster=*.cern.ch'"
                           " | grep -E -o '[a-zA-Z0-9.-]+[.]cern[.]ch'"
                           " | sort -u")
  if error:
    return None
  return out.split("\n")

def gridReleases(ce):
  error, out = withGridEnv("lcg-tags --vo cms --ce %(ce)s --list", ce=ce)
  if error:
    return None
  return ["CMSSW_" + x.split("CMSSW_")[1] 
          for x in out.split("\n") 
          if "CMSSW_" in x]

def announceRelease(ce, release):
  error, out = withGridEnv("lcg-tags --ce %(ce)s --vo cms --add --tags VO-cms-%(release)s",
                           ce=ce,
                           release=release) 
  return (release, error)

if __name__ == "__main__":
  parser = OptionParser(usage="%(prog)s")
  announced = getAnnouncedReleases({"release_type": "Production",
                                    "release_state": "Announced"})
  if not announced:
    parser.error("Could not connect to the tagcollector")

  error, out = withGridEnv("voms-proxy-init -voms %(voms)s",
                            voms="cms:/cms/Role=lcgadmin")
  if error:
    parser.error("Could not get a proxy")

  ces = availableCes()
  if not ces:
    parser.error("Could not find any CE")

  grids = gridReleases(ces[0])
  missingReleases = [x for x in announced if x not in grids]
  if not missingReleases:
    print "No releases to announce"
    exit(0)

  errors = []
  for ce in ces:
    announced = [announceRelease(ce, x) for x in missingReleases]
    errors += ["Release %s cannot be announced on %s" % (x,ce)
               for (x, err) in announced if err]
    ok = ["Release %s announced." % (x,ce)
          for (x, err) in announced if err] 
    if not errors:
      print "\n".join(ok)
      break

    print "\n".join(errors)
